# Generated by Django 3.0.6 on 2020-09-20 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hadid', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('merchant_identifier', models.CharField(max_length=20)),
                ('custname', models.CharField(max_length=30)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('amount', models.IntegerField()),
                ('command', models.CharField(default='PURCHASE', max_length=30)),
                ('order_description', models.TextField(default='iPhone 6-S')),
                ('currency', models.CharField(default='AED', max_length=40)),
                ('language', models.CharField(default='en', max_length=40)),
                ('customer_email', models.EmailField(default='test@payfort.com', max_length=40)),
                ('access_code', models.CharField(default='rxaCBohhRdmZopQxc4gu', max_length=40)),
                ('merchant_reference', models.CharField(default='', max_length=30)),
                ('signature', models.CharField(default='', max_length=30)),
            ],
        ),
    ]
